name: Webook Monitor

on:
  workflow_dispatch:

# يمنع التشغيل المتوازي نهائياً ويجبر الـ Workflow على الانتظار حتى ينتهي الحالي
concurrency:
  group: webook-monitor-single
  cancel-in-progress: false

permissions:
  actions: write
  contents: write

jobs:
  check-webook:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright requests
        playwright install chromium

    - name: Run Webook monitor script
      env:
        TELE_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELE_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        WEBOOK_EMAIL: ${{ secrets.WEBOOK_EMAIL }}
        WEBOOK_PASS: ${{ secrets.WEBOOK_PASS }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: python main.py

    - name: Trigger Next Run Automatically
      if: success()
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [ -f "stop_signal.txt" ]; then
          echo "🛑 تم إرسال تنبيه فتح التذاكر! يتم إيقاف التكرار التلقائي الآن."
        else
          echo "🔄 جاري إطلاق تشغيل جديد متسلسل..."
          # انتظار ثانيتين لضمان إغلاق الجلسة السابقة
          sleep 2
          gh workflow run "Webook Monitor"
        fi
